version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    expose:
      - "5432"
    volumes:
      - db-config:/etc/postgresql
      - db-log:/var/log/postgresql
      - db-data:/var/lib/postgresql
volumes:
  db-config:
    external: false
  db-log:
    external: false
  db-data:
    external: false
