version: '2'
services:
  store:
    build:
      context: .
      dockerfile: Dockerfile.pg
    expose:
      - "5432"
    volumes:
      - db-config:/etc/postgresql
      - db-log:/var/log/postgresql
      - db-data:/var/lib/postgresql
    container_name: monopoly-store
  server:
    image: monopoly_server
    depends_on:
      - store
    ports:
      - "8000:8000"
    command: /usr/local/bin/monopoly-server
    container_name: monopoly-server
volumes:
  db-config:
    external: false
  db-log:
    external: false
  db-data:
    external: false
