.PHONY: build-res build-docs help run build-schemas clean-stack \
		clean-target clean-all run purge-db build-samples

APP_NAME=Monopoly Server

DB_PORT_HOST=8001
SERVER_ADDRESS=localhost:8000

.DEFAULT_GOAL:=help

run-server: ## Run the Monopoly server and backing PostgreSQL instance.
run-server: up-docker-pg
	stack build
	stack exec monopoly-server

help: ## Show this help
	@echo "Makefile for '${APP_NAME}'\n"
	@fgrep -h "##" $(MAKEFILE_LIST) | \
	fgrep -v fgrep | sed -e 's/## */##/' | column -t -s##

load-locations: ## Load locations in YAML to the server.
load-locations: target/samples/locations.json
	curl ${SERVER_ADDRESS}/locations -H 'Content-Type: application/json' \
		 -d @$<

load-questions: ## Loads questions in YAML to the server.
load-questions: target/samples/questions.json
	curl ${SERVER_ADDRESS}/cards -H 'Content-Type: application/json' \
		 -d @$<

load-team: # Loads a team into the server.
load-team: target/samples/team-1.json
	curl ${SERVER_ADDRESS}/teams -H 'Content-Type: application/json' \
		 -d @$<

load-all: ## Loads all resources into the server.
load-all: load-locations load-questions load-team

do-visit:
	curl -X 'POST' ${SERVER_ADDRESS}/locations/${location}/visit/${team}

build-all: ## Build everything
build-all: build-server build-docs

build-server: ## Build the server using Haskell Stack
	@stack build

build-res: ## Generate target files from resource files
build-res: build-schemas build-samples build-docs

build-docs: ## Generate html documentation
build-docs: target/docs/monopoly.html

build-schemas: ## Convert JSON schemas specified in YAML to JSON
build-schemas:

build-docker-pg: ## Build the PostgreSQL docker image.
	docker build -t bartfrenk/monopoly-pg -f Dockerfile.pg .

up-docker-pg: ## Run monopoly-pg in the background. Create it if it doesn't exist.
	@docker create -p ${DB_PORT_HOST}:5432 --name monopoly-pg \
			bartfrenk/monopoly-pg 2> /dev/null; \
	docker start monopoly-pg

# TODO: autogenerate targets
build-samples: target/samples/locations.json \
			   target/samples/team-1.json \
			   target/samples/questions.json

clean-all: ## Remove all generated files
clean-all: clean-target clean-stack

clean-target: ## Remove all files generated from resources
	@rm -rf target

clean-stack: ## Removes files generated by Haskell Stack
	@stack clean

purge-db: ## Drop all tables from monopoly database
	-psql -U monopoly -d monopoly -f res/sql/clean-db.sql

target/docs/monopoly.html: res/docs/monopoly.raml target/docs \
						   build-samples build-schemas
	raml2html $< > $@

target/samples/%.json: res/samples/%.yaml target/samples
	@python -c \
		'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' \
		< $< > $@

target/docs:
	@mkdir -p target/docs

target/samples:
	@mkdir -p target/samples



